#!/bin/bash

while read config; do
    conf=/9ecbf/config/$config.conf
    [[ -f $conf ]] && source $conf &> /dev/null
done < /9ecbf/config/ENABLED

source /9ecbf/config/git.conf

export PATH=$PATH:/9ecbf/bin
bind 'TAB:menu-complete'

[[ "$PWD" == "/mnt"* ]] && cd ~ || test true
